name: Bazel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      # Build your program with gcc
      working-directory: ${{github.workspace}}
      run: bazel build --action_env=CXX=g++ --action_env=CC=gcc ...

    - name: Test
      # Build and Execute tests
      working-directory: ${{github.workspace}}
      run: bazel test --action_env=CXX=g++ --action_env=CC=gcc --test_output=errors ...